server:
  port: 9090
spring:
  application:
    name: demo-app
  datasource:
    url: jdbc:postgresql://localhost:5432/api_sso_auth_db
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:api_sso_user}
    password: ${DB_PASSWORD:api_sso_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  # Keycloak  configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/myrealm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/myrealm/protocol/openid-connect/certs}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:myrealm}
  resource: ${KEYCLOAK_CLIENT_ID:admin-cli}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}